import type { Order } from "./types";
import type { DashboardTableColumn } from "@/src/components/common/dashboard-data-table";

export const initialOrders: Order[] = [
  {
    id: "DH-1055",
    customer: "Nguyễn Thị Hương",
    service: "Giặt thường",
    quantity: "4.6 kg",
    deliveryDate: "2026-06-10",
    deliveryTime: "16:00",
    staff: "Nguyễn Diệu Lynh",
    amount: 92000,
    status: "Hoàn thành",
    note: "Giặt riêng đồ sáng màu, không sấy khô",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-06-08",
  },

  {
    id: "DH-1048",
    customer: "Nguyễn Thị Hương",
    service: "Giặt ủi",
    quantity: "3.2 kg",
    deliveryDate: "2026-06-07",
    deliveryTime: "09:00",
    staff: "Trần Văn Bình",
    amount: 128000,
    status: "Hoàn thành",
    note: "Ủi cẩn thận áo sơ mi",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-06-05",
  },

  {
    id: "DH-1039",
    customer: "Nguyễn Thị Hương",
    service: "Giặt khô",
    quantity: "2 món",
    deliveryDate: "2026-06-04",
    deliveryTime: "14:00",
    staff: "Lê Thị Mai",
    amount: 210000,
    status: "Hoàn thành",
    note: "Vest và áo blazer, xử lý vết bẩn",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-06-02",
  },

  {
    id: "DH-1033",
    customer: "Nguyễn Thị Hương",
    service: "Giặt nhanh",
    quantity: "2.0 kg",
    deliveryDate: "2026-06-02",
    deliveryTime: "11:30",
    staff: "Chưa gán",
    amount: 75000,
    status: "Chờ thanh toán",
    note: "",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-06-01",
  },

  {
    id: "DH-1021",
    customer: "Nguyễn Thị Hương",
    service: "Giặt ủi",
    quantity: "5.1 kg",
    deliveryDate: "2026-05-28",
    deliveryTime: "15:00",
    staff: "Nguyễn Diệu Lynh",
    amount: 204000,
    status: "Hoàn thành",
    note: "Giặt riêng đồ màu trắng",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-05-26",
  },

  {
    id: "DH-1010",
    customer: "Nguyễn Thị Hương",
    service: "Giặt thường",
    quantity: "3.8 kg",
    deliveryDate: "2026-05-22",
    deliveryTime: "10:00",
    staff: "Trần Văn Bình",
    amount: 76000,
    status: "Tiếp nhận",
    note: "Khách hủy do thay đổi lịch",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-05-20",
  },

  {
    id: "DH-1062",
    customer: "Nguyễn Thị Hương",
    service: "Giặt ủi cao cấp",
    quantity: "1 bộ",
    deliveryDate: "2026-06-12",
    deliveryTime: "09:00",
    staff: "Lê Thị Mai",
    amount: 350000,
    status: "Đã xác nhận lịch",
    note: "Bộ vest cưới, xử lý đặc biệt",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-06-08",
  },

  {
    id: "DH-1058",
    customer: "Nguyễn Thị Hương",
    service: "Giặt nhanh",
    quantity: "1.5 kg",
    deliveryDate: "2026-06-09",
    deliveryTime: "18:00",
    staff: "Nguyễn Diệu Lynh",
    amount: 55000,
    status: "Đang giặt",
    note: "Giao tại quầy",
    phone: "0901 234 567",
    address: "12 Nguyễn Trãi, Q.1, TP.HCM",
    createdAt: "2026-06-08",
  },
];


export const defaultColumns: DashboardTableColumn[] = [
  { id: "id", label: "Mã đơn", width: 130, visible: true },
  { id: "customerCode", label: "Mã KH", width: 110, visible: true },
  { id: "customer", label: "Khách hàng", width: 180, visible: true },
  { id: "phone", label: "Số điện thoại", width: 120, visible: true },
  { id: "address", label: "Địa chỉ", width: 180, visible: false },
  { id: "service", label: "Dịch vụ", width: 120, visible: true },
  { id: "quantity", label: "Số lượng", width: 110, visible: true },
  { id: "unitPrice", label: "Đơn giá", width: 120, visible: true },
  { id: "originalAmount", label: "Giá gốc", width: 120, visible: true },
  { id: "washer", label: "Máy giặt", width: 110, visible: true },
  { id: "dryer", label: "Máy sấy", width: 110, visible: true },
  { id: "amount", label: "Thành tiền", width: 120, visible: true },
  { id: "deliveryDate", label: "Ngày giao", width: 110, visible: true },
  { id: "deliveryTime", label: "Giờ giao", width: 100, visible: true },
  { id: "staff", label: "Nhân viên", width: 160, visible: true },
  { id: "status", label: "Trạng thái", width: 150, visible: true },
  { id: "createdAt", label: "Ngày tạo đơn", width: 120, visible: true },
  { id: "payment", label: "Thanh toán", width: 120, visible: false },
  { id: "discount", label: "Mã giảm giá", width: 120, visible: true },
  { id: "discountValue", label: "Ưu đãi", width: 120, visible: true },
  { id: "note", label: "Ghi chú", width: 180, visible: true },
  { id: "actions", label: "Thao tác", width: 220, visible: true },
];

